services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: smarteconomato_nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: smarteconomato_frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: smarteconomato_backend
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://admin:admin@db:5432/smart_economato?schema=public
      JWT_SECRET: palabra_secreta_para_firmar_tokens_123
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: smarteconomato_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smart_economato
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smart_economato"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data: