FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update \
	&& apt-get install -y --no-install-recommends openssl \
	&& rm -rf /var/lib/apt/lists/*

COPY EconomatoBack/package*.json ./
COPY EconomatoBack/prisma ./prisma
RUN npm ci

COPY EconomatoBack ./

RUN npx prisma generate

EXPOSE 3000

CMD ["npx", "ts-node", "src/index.ts"]
